## Q. Create an array. Take input number from user. Find it in array. Give its location. Give its count. Replace the number with its squareroot.

In [1]:
def Searcher():
    #importing required libraries
    import numpy as np
    import math
    
    #creating array containg 100 integers from 1 to 50
    Array = []
    for i in range(0,100):
        Array.append(np.random.randint(1,51))
    print("The originial array is\n", Array[:])   
    
    #taking an input from user
    a = int(input("\nEnter a number:"))
    if a>50:
        print("Please enter a number from 1 to 50.\n")
        
    #getting count and location of the number in the array and replacing it with its squareroot    
    if a in Array:
        print(a, "occures", Array.count(a),"times in the Array.\n")
        indices = [i for i in range(len(Array)) if Array[i] == a]
        print(a,"occures at indices", indices[:],".\n")
        for x in indices:
            Array[x] = math.sqrt(a)
        print("After replacing", a,"by its square root", math.sqrt(a),"the new array will be\n\n",Array[:]) 
    else: 
        print(a,"does not exist in Array.")
Searcher()

The originial array is
 [15, 38, 29, 7, 26, 41, 21, 30, 38, 34, 1, 20, 45, 27, 50, 43, 22, 14, 43, 14, 48, 15, 23, 1, 26, 44, 17, 26, 45, 29, 18, 48, 48, 31, 16, 41, 37, 21, 21, 15, 44, 50, 49, 44, 12, 46, 42, 8, 13, 29, 9, 44, 48, 50, 26, 14, 1, 23, 43, 49, 31, 44, 2, 28, 6, 19, 50, 8, 22, 32, 42, 35, 34, 1, 12, 36, 12, 25, 43, 42, 43, 47, 22, 38, 27, 25, 17, 34, 33, 50, 26, 37, 17, 41, 49, 12, 11, 21, 1, 16]

Enter a number:43
43 occures 5 times in the Array.

43 occures at indices [15, 18, 58, 78, 80] .

After replacing 43 by its square root 6.557438524302 the new array will be

 [15, 38, 29, 7, 26, 41, 21, 30, 38, 34, 1, 20, 45, 27, 50, 6.557438524302, 22, 14, 6.557438524302, 14, 48, 15, 23, 1, 26, 44, 17, 26, 45, 29, 18, 48, 48, 31, 16, 41, 37, 21, 21, 15, 44, 50, 49, 44, 12, 46, 42, 8, 13, 29, 9, 44, 48, 50, 26, 14, 1, 23, 6.557438524302, 49, 31, 44, 2, 28, 6, 19, 50, 8, 22, 32, 42, 35, 34, 1, 12, 36, 12, 25, 6.557438524302, 42, 6.557438524302, 47, 22, 38, 27, 25, 17, 34, 33, 50,

## Q. Take two 2-dimentional arrays and merge them with increasing order of numbers.

In [2]:
def Merger():
    import numpy as np
    import pandas as pd
    array1 = []
    array2 = []
    for i in range(0,9):
        array1.append(np.random.randint(1,20))
        array2.append(np.random.randint(1,20))
    a = np.array(array1)
    b = np.array(array2)
    array_2D_1 = a.reshape((3,3))
    array_2D_2 = b.reshape((3,3))
    final = []
    for x in array_2D_1:
        for y in x:
            final.append(y)
    for x in array_2D_2:
        for y in x:
            final.append(y)
    final.sort()  
    sorted_final = np.array(final).reshape(6,3)
    print("Merged array of\n", array_2D_1, "\nand\n", array_2D_2, "\nis:\n", sorted_final)
Merger()

Merged array of
 [[ 6 17 18]
 [ 7  9 12]
 [11 18  4]] 
and
 [[12  1 19]
 [ 2 11  2]
 [ 1  2 14]] 
is:
 [[ 1  1  2]
 [ 2  2  4]
 [ 6  7  9]
 [11 11 12]
 [12 14 17]
 [18 18 19]]
